[package]
name = "tokio-beanstalkd"
version = "0.5.0"
authors = ["Bhargav Voleti <bhargav.voleti93@gmail.com>"]
edition = "2018"

description = "Asynchronous client library for interacting with Beanstalkd work queue."
readme = "README.md"

homepage = "https://github.com/bIgBV/tokio-beanstalkd"
repository = "https://github.com/bIgBV/tokio-beanstalkd"

keywords = ["beanstalkd", "tokio", "asynchronous"]
categories = ["api-bindings", "asynchronous", "network-programming"]

license = "MIT"

[dependencies]
tokio = { version = "0.2.22", features = ["macros", "net"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
futures = { version = "0.3.5", features = ["std"] }
futures-core = "0.3.5"
futures-util = "0.3.5"
failure = "0.1.8"
bytes = "0.5.6"
